//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWicket.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public System.Guid Id { get; set; }
        public System.Guid VisitorId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
