//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SmartWicket.DataBase.Objects;

namespace SmartWicket.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit: Entity
    {
        [Display(Name ="Посетитель")]
        public System.Guid VisitorId { get; set; }
        [Display(Name = "Дата посещения")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime VisitDate { get; set; }

        [Display(Name = "Дата создания посещения")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
